export const defaultSettings = {
  institutionName: '',
  affiliation: '',
  address: '',
  phone: '',
  email: '',
  website: '',
  naacGrade: '',
  collegeLogo: '',
  principalName: '',
  establishedYear: '',
  aisheCode: '',
  autonomousStatus: '',
  collegeType: '',
  motto: '',
  headerFont: 'Arial',
  bodyFontSize: '12pt',
  pageMargins: '15mm',
  qrVerification: 'Enabled',
  jwtExpiry: '15 minutes',
  refreshExpiry: '7 days',
  bcryptCost: '12',
  httpsEnforcement: 'Enabled',
  autoBackup: 'Daily at 2:00 AM',
  retentionPeriod: '30 days',
};

export const defaultState = {
  setupDone: false,
  departments: [],
  faculty: [],
  subjects: [],
  classrooms: [],
  students: [],
  exams: [],
  notifications: [],
  audit: [],
  timetable: [],
  seats: [],
  attendanceHistory: [],
  documents: [],
  settings: defaultSettings,
};
